### ISSUE TITLE
이더스캔 API 멀티프로세싱 함수 구현

### ISSUE THREAD

**Issue by syleeie2310** [syleeie2310/nft_dataanalysis#23]
라이브러리 기반 또는 본인 이 짠 함수로 해도 되고

**Comment by parkdonghwan97** [comment]
생각보다  공부할 내용이 많음,, 코드 예제도 제대로 돌아가는게 별로 없음. 공부 더 필요함

**Comment by parkdonghwan97** [comment]
![image](https://user-images.githubusercontent.com/64680900/155680427-7294d7be-8d9b-40b7-a9ff-57dd6b2b98ab.png)

**Comment by parkdonghwan97** [comment]
멀티프로세싱

1.  멀티프로세싱(x)
-> 1, 2 3 함수 3개 835.9167385101318 초

2.  멀티프로세싱(o) -   parmap 사용  x, 
-> 1, 2 3 함수 3개  621.74초

3. 멀티프로세싱(o)
- parmap 사용하면 228초
- parmpa 사용 안하면 218초

**Comment by parkdonghwan97** [comment]
몇 번 더 해봐도 시간 차이 별로 없는 것 같은데 함수가 단순해서그런가.. 일단 이대로 진행 해보겠음

**Comment by parkdonghwan97** [comment]
![image](https://user-images.githubusercontent.com/64680900/156298030-d90040de-5e04-41bc-9dfc-b34d08103644.png)
멀티프로세스로 코드 짜보니 속도 제한이 생김 .. 수정 필요

**Comment by parkdonghwan97** [comment]
https://github.com/syleeie2310/nft_dataanalysis/blob/main/Multiprocessing_example/Ex_1.py
